### ISSUE TITLE
MAPA MENTAL_GENARO SANTIAGO VALENTÍN

### ISSUE THREAD

**Issue by Valentiin01** [SistemasTecTlaxiaco/ACTIVIDAD1--MAPA-MENTAL-#1]
[GENARO SANTIAGO VALENTÍN_MAPA MENTAL.pdf](https://github.com/SistemasTecTlaxiaco/ACTIVIDAD1--MAPA-MENTAL-/files/10726304/GENARO.SANTIAGO.VALENTIN_MAPA.MENTAL.pdf)

**Comment by ang3-l32** [comment]
CALIFICACIÓN: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
